### ISSUE TITLE
What does MODEL.NUM_CLASSES in mask_textspotter.yaml mean?

### ISSUE THREAD

**Issue by Ocelot7777** [lvpengyuan/masktextspotter.caffe2#13]
Why it's set 2 instead of 36. Text/Non-Text?

**Comment by lvpengyuan** [comment]
> Why it's set 2 instead of 36. Text/Non-Text?

Yes, it means Text/Non-Text. You can modify the mask branch's num_cls in https://github.com/lvpengyuan/masktextspotter.caffe2/blob/11efca569d81faed47de0b63d3fff3d5bc439cfe/lib/modeling/text_mask_rcnn_heads.py#L50

**Comment by Ocelot7777** [comment]
> > Why it's set 2 instead of 36. Text/Non-Text?
> 
> Yes, it means Text/Non-Text. You can modify the mask branch's num_cls in
> 
> [masktextspotter.caffe2/lib/modeling/text_mask_rcnn_heads.py](https://github.com/lvpengyuan/masktextspotter.caffe2/blob/11efca569d81faed47de0b63d3fff3d5bc439cfe/lib/modeling/text_mask_rcnn_heads.py#L50)
> 
> Line 50 in [11efca5](/lvpengyuan/masktextspotter.caffe2/commit/11efca569d81faed47de0b63d3fff3d5bc439cfe)
> 
>  num_cls = 37

thanks！
