### ISSUE TITLE
I guess there is something wrong with _get_dataset_inds(self) in mix_loader.py, line 146

### ISSUE THREAD

**Issue by Ocelot7777** [lvpengyuan/masktextspotter.caffe2#14]
1. When I set MIX_RATIOS = [0.4, 0.4, 0.2] in .yaml, it stop at assert(len(self._dataset_inds) == self._num_gpus*cfg.TRAIN.IMS_PER_BATCH).  And self._dataset_inds = [].

2. Then I set MIX_RATIOS = [2.0, 2.0, 1.0] in .yaml and comment the assert, since self._dataset_inds = [0, 0, 1, 1, 2]. It seems to work as expect.

3. So do you have any idea? Or would you please explain the assert?

**Comment by lvpengyuan** [comment]
Hi, how many GPUs do you use? In our experiment, we set the batch_size to 8 (4 GPUs) and the mix_ratio to [0.125, 0.125, 0.5, 0.125, 0.125] to sample samples from each dataset.

your solution can also work.

**Comment by Ocelot7777** [comment]
> Hi, how many GPUs do you use? In our experiment, we set the batch_size to 8 (4 GPUs) and the mix_ratio to [0.125, 0.125, 0.5, 0.125, 0.125] to sample samples from each dataset.
> 
> your solution can also work.
Two. Now I know why I got the previous mistake. Thanks!
