### ISSUE TITLE
ImportError: No module named lanms

### ISSUE THREAD

**Issue by huziling** [lvpengyuan/masktextspotter.caffe2#18]
I try python tools/test_net.py --cfg configs/text/mask_textspotter.yaml
but i can not import lanms
i have all ready make in lib and make in masktextspotter.caffe2/lanms

i use anaconda3 python2.7
gcc and g++ version is 5.4

**Comment by weiyaowu666** [comment]
I'm also encounter this problem, have you solved it?

**Comment by huziling** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    在错误的文件中 添加lanms的路径
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                278820314
                            
                    
                        
                            
                                    278820314@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 3/10/2019 18:32，yaowu<notifications@github.com> wrote： 


I'm also encounter this problem, have you solved it?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by huziling** [comment]
在错误的文件中 添加lanms的路径

> 
> 
> I'm also encounter this problem, have you solved it?

**Comment by weiyaowu666** [comment]
应该怎么加呢，我试了一下，没成功，还是一样， no module named lanms,   能给个代码嘛，多谢啦

**Comment by huziling** [comment]
> 
> 
> 应该怎么加呢，我试了一下，没成功，还是一样， no module named lanms, 能给个代码嘛，多谢啦

我的 写法是 在报错的文件中加入
import sys
sys.path.append('//mnt//Maxtextspottrt')

**Comment by weiyaowu666** [comment]
thank you very much,   解决了刚刚那个问题，又出现了一个Caffe2版本没有Detectron module的问题，我去更新一下，多谢

**Comment by weiyaowu666** [comment]
> > 应该怎么加呢，我试了一下，没成功，还是一样， no module named lanms, 能给个代码嘛，多谢啦
> 
> 我的 写法是 在报错的文件中加入
> import sys
> sys.path.append('//mnt//Maxtextspottrt')


解决不了，安装了Detectron之后，又出现core.config问题
Traceback (most recent call last):
  File "tools/train_net.py", line 35, in <module>
    import test_net
  File "/workspace/mnt/group/fd-students/weiyaowu/masktextspotter.caffe2/tools/test_net.py", line 34, in <module>
    from core.config import assert_and_infer_cfg
ImportError: No module named core.config

**Comment by huziling** [comment]
> > > 应该怎么加呢，我试了一下，没成功，还是一样， no module named lanms, 能给个代码嘛，多谢啦
> > 
> > 
> > 我的 写法是 在报错的文件中加入
> > import sys
> > sys.path.append('//mnt//Maxtextspottrt')
> 
> 解决不了，安装了Detectron之后，又出现core.config问题
> Traceback (most recent call last):
> File "tools/train_net.py", line 35, in 
> import test_net
> File "/workspace/mnt/group/fd-students/weiyaowu/masktextspotter.caffe2/tools/test_net.py", line 34, in 
> from core.config import assert_and_infer_cfg
> ImportError: No module named core.config

差不多的道理 
import sys
sys.path.append('//mnt//Maxtextspottrt//lib')
你可以
print(sys.path)
看看是否python路径中是否不包含这个路径

**Comment by ghost** [comment]
@lvpengyuan @huziling @weiyaowu-md 
Can someone explain in English how to solve this :
```
ImportError: No module named lanms
```

**Comment by ghost** [comment]
@MhLiao
