### ISSUE TITLE
format of results

### ISSUE THREAD

**Issue by DecentMakeover** [lvpengyuan/masktextspotter.caffe2#24]
Hi 

i don't understand the format of the results, 
`618,140,662,159,618,140,660,140,660,157,618,157,ahead,0.99701583,0.9119489312171936,./train/shrink++_finetune/icdar2015_test/model_iter79999.pkl_results/res_img_1_0.mat` this is one result of the text file.

There are 12 numbers  and then a word and two more numbers, What do the 12 numbers mean?
I checked the icdar data and it has 8 numbers.

also why are there 2 confidence scores?

Any suggestions would be really helpful.

Thanks in advance.

**Comment by zhengjiawen** [comment]
Hi, @DecentMakeover , I also encounter the problem, do you  know the 12 number mean? Thanks a lot.

**Comment by DecentMakeover** [comment]
Nope.No idea.

**Comment by LousyLory** [comment]
the first 12 numbers are the vertices of the bounding polygon.
