### ISSUE TITLE
How get character level annotation ?

### ISSUE THREAD

**Issue by DecentMakeover** [lvpengyuan/masktextspotter.caffe2#28]
Hi 

For training Icdar2013 the ground truth files look this 
for a single word 
 
 
 158.0,128.0,411.0,128.0,411.0,181.0,158.0,181.0,Footpath,158.0,131.0,187.0,131.0,187.0,172.0,158.0,172.0,F,189.0,139.0,219.0,139.0,219.0,171.0,189.0,171.0,o,226.0,139.0,255.0,139.0,255.0,171.0,226.0,171.0,o,261.0,129.0,282.0,129.0,282.0,171.0,261.0,171.0,t,290.0,140.0,319.0,140.0,319.0,181.0,290.0,181.0,p,324.0,139.0,351.0,139.0,351.0,170.0,324.0,170.0,a,357.0,128.0, 377.0,128.0,377.0,170.0,357.0,170.0,t,385.0,129.0,411.0,129.0,411.0,170.0,385.0,170.0,h

as you see this also has charcter level annotation. 

but for the icdar 2015 training set, the annotation looks like this- 

    ﻿377,117,463,117,465,130,378,130,Genaxis Theatre
    493,115,519,115,519,131,493,131,[06]
    374,155,409,155,409,170,374,170,###
    492,151,551,151,551,170,492,170,62-03
    376,198,422,198,422,212,376,212,Carpark
    494,190,539,189,539,205,494,206,###
    374,1,494,0,492,85,372,86,###

As you see this does not have letter level annotation.
can anyone guide me as to how to get charcter level annotation from this?

Thanks in advance.

**Comment by LousyLory** [comment]
i guess this is a open research problem.

**Comment by DecentMakeover** [comment]
Ah, Okay , ill look into it
