### ISSUE TITLE
ImportError: cannot import name test_retinanet

### ISSUE THREAD

**Issue by TBS1234** [lvpengyuan/masktextspotter.caffe2#37]
Traceback (most recent call last):
  File "tools/test_net.py", line 42, in <module>
    from core.test_retinanet import test_retinanet
ImportError: cannot import name test_retinanet
你好，我在detectron的core中的test_retinanet.py中没有找到test_retinanet函数

**Comment by LousyLory** [comment]
Did you solve this? If yes, how?

**Comment by brooklyn1900** [comment]
Same question for me!!
