### ISSUE TITLE
have no json_dataset

### ISSUE THREAD

**Issue by xieyufei1993** [lvpengyuan/masktextspotter.caffe2#5]
ImportError: cannot import name json_dataset
@lvpengyuan

**Comment by oysz2016** [comment]
I meet the same problem,please help!

**Comment by lvpengyuan** [comment]
@xieyufei1993 @oysz2016 Thank you for pointing out the mistake. The missing file has been uploaded.

**Comment by xieyufei1993** [comment]
thanks
