### ISSUE TITLE
have no cityscapes_json_dataset_evaluator

### ISSUE THREAD

**Issue by xgmiao** [lvpengyuan/masktextspotter.caffe2#6]
have no cityscapes_json_dataset_evaluator @lvpengyuan

**Comment by MTaoYue** [comment]
there is the same problem

**Comment by MTaoYue** [comment]
also no voc_dataset_evaluator.py   dataset_catalog.py in datasets

**Comment by yuanyay** [comment]
same as you，please help！

**Comment by lvpengyuan** [comment]
@xgmiao @yuanyay Thank you for pointing out the mistake. The missing file has been uploaded. Please update your code from git.
